### ISSUE TITLE
Theoretical fortune cookie of another language?

### ISSUE THREAD

**Issue by kirkins** [RichardLitt/fortune-cookie-corpus#3]
I haven't gotten a fortune cookie that was only in Chinese or French so this may be a pointless question.

What if you I get a fortune cookie that has no English 🤔 is it allowed here.

**Comment by kirkins** [comment]
I guess you could just add language attribute to the root of the item.

**Comment by RichardLitt** [comment]
Sure. We should probably change the format:

```json
[
{
"text": "Follow your dreams.",
"language": "English."
},
{
"text": "suis tes rêves",
"language": "Francais"
}
]
```

**Comment by RichardLitt** [comment]
Reformated.
